import { loadCore, countState } from './store.mjs'
import { renderJournal } from './journal.mjs'

/**
 * Build a portable context pack for any LLM / AI chat product.
 * No vendor lock-in: paste into ChatGPT, Claude, Grok, Cursor, etc.
 */
export function buildWakePack(home, { refreshJournal = true } = {}) {
  if (refreshJournal) {
    try {
      renderJournal(home)
    } catch {
      /* keep existing journal */
    }
  }

  const core = loadCore(home)
  if (!core.exists) {
    return {
      text: `# PROXY JOURNAL — not initialized

Run:

\`\`\`bash
npx proxy-journal init
# or: node bin/proxy-journal.mjs init
\`\`\`

Then run \`proxy-journal wake\` again and paste the output into your AI chat.
`,
      core,
    }
  }

  const id = core.identity
  const mem = core.memory
  const name = id?.name || 'Proxy'
  const recentJson = JSON.stringify(core.recent, null, 2)
  const memoryJson = JSON.stringify(mem, null, 2)
  const identityJson = JSON.stringify(id, null, 2)

  const text = `# PROXY JOURNAL — Wake / Bootstrap Pack

You are **${name}**, a persistent development companion.
This pack restores your identity, memory, and recent progress so you are **not a blank slate**.

---

## Your standing rules

${(id?.rules || []).map((r) => `- ${r}`).join('\n') || '- Log progress. Rebuild from memory if context was lost.'}

---

## Identity (JSON)

\`\`\`json
${identityJson}
\`\`\`

---

## Memory (JSON)

\`\`\`json
${memoryJson}
\`\`\`

---

## Recent state (last ${core.recent.length} of ${countState(home)} events)

\`\`\`json
${recentJson}
\`\`\`

---

## Living journal (markdown)

${core.journal || '_journal.md empty — will regenerate on preserve_'}

---

## Open loops (unfinished work)

${
    Array.isArray(mem?.open_loops) && mem.open_loops.length
      ? mem.open_loops
          .map((l) =>
            typeof l === 'string'
              ? `- [ ] ${l}`
              : `- [ ] **${l.title}**${l.note ? ` — ${l.note}` : ''}`
          )
          .join('\n')
      : '_None tracked._'
  }

---

## Durable facts

\`\`\`json
${JSON.stringify(mem?.facts || {}, null, 2)}
\`\`\`

---

## Operator instructions for this chat

1. Acknowledge that you loaded this journal (name yourself **${name}**).
2. Summarize the last known work in 3–5 bullets, and list any open loops.
3. Ask what to continue — do not invent history that is not in memory/state.
4. When the operator finishes a milestone, they will log it with:
   \`proxy-journal log milestone "…"\` and \`proxy-journal remember "Title" "Description"\`
5. Track unfinished work with \`proxy-journal open\` / \`close\`; store durable truths with \`proxy-journal fact\`.
6. Prefer concrete next steps over vague encouragement.

---

*Generated by PROXY JOURNAL · DIGIVASCONNECT PTY (LTD)*
*Home: \`${home}\` · ${new Date().toISOString()}*
`

  return { text, core }
}
